# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hx4_patch',
                'doc_host': 'https://dienhoa.github.io',
                'git_url': 'https://github.com/dienhoa/hx4_patch',
                'lib_path': 'hx4_patch'},
  'syms': { 'hx4_patch.core': { 'hx4_patch.core.FastHTML.__init__': ('core.html#fasthtml.__init__', 'hx4_patch/core.py'),
                                'hx4_patch.core.Partial': ('core.html#partial', 'hx4_patch/core.py'),
                                'hx4_patch.core._app_factory': ('core.html#_app_factory', 'hx4_patch/core.py'),
                                'hx4_patch.core._get_tbl': ('core.html#_get_tbl', 'hx4_patch/core.py'),
                                'hx4_patch.core.def_hdrs': ('core.html#def_hdrs', 'hx4_patch/core.py'),
                                'hx4_patch.core.fast_app': ('core.html#fast_app', 'hx4_patch/core.py')}}}
