# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hx4_patch',
                'doc_host': 'https://dienhoa.github.io',
                'git_url': 'https://github.com/dienhoa/hx4_patch',
                'lib_path': 'hx4_patch'},
  'syms': { 'hx4_patch.core': { 'hx4_patch.core.FastHTML.__init__': ('core.html#fasthtml.__init__', 'hx4_patch/core.py'),
                                'hx4_patch.core.Partial': ('core.html#partial', 'hx4_patch/core.py'),
                                'hx4_patch.core._find_p': ('core.html#_find_p', 'hx4_patch/core.py'),
                                'hx4_patch.core._wrap_ws': ('core.html#_wrap_ws', 'hx4_patch/core.py'),
                                'hx4_patch.core.def_hdrs': ('core.html#def_hdrs', 'hx4_patch/core.py'),
                                'hx4_patch.core.fast_app': ('core.html#fast_app', 'hx4_patch/core.py'),
                                'hx4_patch.core.sse_message': ('core.html#sse_message', 'hx4_patch/core.py')}}}
