# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hx4_patch',
                'doc_host': 'https://dienhoa.github.io',
                'git_url': 'https://github.com/dienhoa/hx4_patch',
                'lib_path': 'hx4_patch'},
  'syms': { 'hx4_patch.core': { 'hx4_patch.core.Partial': ('core.html#partial', 'hx4_patch/core.py'),
                                'hx4_patch.core.fast_app_v4': ('core.html#fast_app_v4', 'hx4_patch/core.py')}}}
