"""HTMX v4 support for FastHTML"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['empty', 'htmx4src', 'Partial', 'def_hdrs', 'fast_app', 'PicoBusy4', 'sse_message']

# %% ../nbs/00_core.ipynb #f412b439
#| export
#| default_exp core

# %% ../nbs/00_core.ipynb #54b1bfb3
import json

from fastcore.basics import patch
from fastcore.utils import *
from fastcore.xml import *
from fastcore.meta import delegates

from fasthtml.common import *
from fasthtml.starlette import *
from fasthtml.core import *

from fasthtml.core import _wrap_ex, _list, _get_htmx, _fix_anno, _wrap_ws, _params, _handle, _ws_endp, _find_ps, _is_body, _from_body, snake2hyphens, ApiReturn
from fasthtml.fastapp import _get_tbl, _app_factory

# %% ../nbs/00_core.ipynb #8f4e445b
from inspect import Parameter
empty = Parameter.empty

import fasthtml.core as _core
from fasthtml.core import _send_ws

from typing import Optional, get_type_hints, get_args, get_origin, Union, Mapping, TypedDict, List, Any
from types import UnionType, SimpleNamespace as ns, GenericAlias
from datetime import datetime,date

# %% ../nbs/00_core.ipynb #b37613cb
@delegates(ft_hx)
def Partial(*args, **kwargs): return ft_hx("hx-partial")(*args, **kwargs)


# %% ../nbs/00_core.ipynb #5b899007
htmx4src   = Script(src="https://unpkg.com/htmx.org@4.0.0-alpha7/dist/htmx.js")

# %% ../nbs/00_core.ipynb #23a4ce68
# When htmx4=True, configures htmx v4 with metaCharacter="-"
def def_hdrs(htmx=True, htmx4=False, surreal=True):
    "Default headers for a FastHTML app"
    hdrs = []
    if surreal: hdrs = [surrsrc,scopesrc] + hdrs
    if htmx and htmx4: raise ValueError("Cannot enable both htmx and htmx4")
    if htmx: hdrs = [htmxsrc,fhjsscr] + hdrs
    if htmx4: 
        # metaCharacter="-" makes htmx4 use dashes instead of colons (Python-friendly)
        meta_cfg = Meta(name="htmx:config", content=json.dumps({"metaCharacter": "-"}))
        hdrs = [meta_cfg, htmx4src,fhjsscr] + hdrs 
    # TODO: Check if fhjsscr works with htmx4
    return [charset, viewport] + hdrs

# %% ../nbs/00_core.ipynb #940ad1bd
# Patch FastHTML.__init__ to add htmx4 support
# - Adds `htmx4` parameter to toggle htmx v4 headers
# - Add self.htmx4
# - Passes htmx4 to def_hdrs() which handles the header selection
# - Maps 'ws' and 'ws4' extensions to 'ws4' when htmx4=True
@patch
def __init__(self: FastHTML, debug=False, routes=None, middleware=None, title: str = "FastHTML page", exception_handlers=None,
                on_startup=None, on_shutdown=None, lifespan=None, hdrs=None, ftrs=None, exts=None,
                before=None, after=None, surreal=True, htmx=True, htmx4=False, default_hdrs=True, sess_cls=SessionMiddleware,
                secret_key=None, session_cookie='session_', max_age=365*24*3600, sess_path='/',
                same_site='lax', sess_https_only=False, sess_domain=None, key_fname='.sesskey',
                body_wrap=noop_body, htmlkw=None, nb_hdrs=False, canonical=True, **bodykw):
    middleware,before,after = map(_list, (middleware,before,after))
    self.title,self.canonical,self.session_cookie,self.key_fname = title,canonical,session_cookie,key_fname
    self.htmx4 = htmx4
    hdrs,ftrs,exts = map(listify, (hdrs,ftrs,exts))
    if htmx4 and exts:
        exts = ['ws4' if e in ('ws', 'ws4') else e for e in exts]
    exts = {k:htmx_exts[k] for k in exts}
    htmlkw = htmlkw or {}
    if default_hdrs: hdrs = def_hdrs(htmx, htmx4, surreal=surreal) + hdrs
    hdrs += [Script(src=ext) for ext in exts.values()]
    if IN_NOTEBOOK:
        hdrs.append(iframe_scr) # TODO: check iframe_scr if work with htmx4
        from IPython.display import display,HTML
        if nb_hdrs: display(HTML(to_xml(tuple(hdrs))))
        middleware.append(cors_allow)
    on_startup,on_shutdown = listify(on_startup) or None,listify(on_shutdown) or None
    self.lifespan,self.hdrs,self.ftrs = lifespan,hdrs,ftrs
    self.body_wrap,self.before,self.after,self.htmlkw,self.bodykw = body_wrap,before,after,htmlkw,bodykw
    self.secret_key = get_key(secret_key, key_fname)
    if sess_cls:
        sess = Middleware(sess_cls, secret_key=self.secret_key,session_cookie=session_cookie,
                            max_age=max_age, path=sess_path, same_site=same_site,
                            https_only=sess_https_only, domain=sess_domain)
        middleware.append(sess)
    exception_handlers = ifnone(exception_handlers, {})
    if 404 not in exception_handlers:
        def _not_found(req, exc): return  Response('404 Not Found', status_code=404)
        exception_handlers[404] = _not_found
    excs = {k:_wrap_ex(v, k, hdrs, ftrs, htmlkw, bodykw, body_wrap=body_wrap) for k,v in exception_handlers.items()}
    super(FastHTML, self).__init__(debug, routes, middleware=middleware, exception_handlers=excs, on_startup=on_startup, on_shutdown=on_shutdown, lifespan=lifespan)

# %% ../nbs/00_core.ipynb #4ea919d9
# Supports htmx4=True for htmx v4 compatibility
def fast_app(
        db_file:Optional[str]=None, # Database file name, if needed
        render:Optional[callable]=None, # Function used to render default database class
        hdrs:Optional[tuple]=None, # Additional FT elements to add to <HEAD>
        ftrs:Optional[tuple]=None, # Additional FT elements to add to end of <BODY>
        tbls:Optional[dict]=None, # Experimental mapping from DB table names to dict table definitions
        before:Optional[tuple]|Beforeware=None, # Functions to call prior to calling handler
        middleware:Optional[tuple]=None, # Standard Starlette middleware
        live:bool=False, # Enable live reloading
        debug:bool=False, # Passed to Starlette, indicating if debug tracebacks should be returned on errors
        title:str="FastHTML page", # Default page title
        routes:Optional[tuple]=None, # Passed to Starlette
        exception_handlers:Optional[dict]=None, # Passed to Starlette
        on_startup:Optional[callable]=None, # Passed to Starlette
        on_shutdown:Optional[callable]=None, # Passed to Starlette
        lifespan:Optional[callable]=None, # Passed to Starlette
        default_hdrs=True, # Include default FastHTML headers such as HTMX script?
        pico:Optional[bool]=None, # Include PicoCSS header?
        surreal:Optional[bool]=True, # Include surreal.js/scope headers?
        htmx:Optional[bool]=True, # Include HTMX header?
        htmx4:Optional[bool]=False, # Include HTMX4 header?
        exts:Optional[list|str]=None, # HTMX extension names to include
        canonical:bool=True, # Automatically include canonical link?
        secret_key:Optional[str]=None, # Signing key for sessions
        key_fname:str='.sesskey', # Session cookie signing key file name
        session_cookie:str='session_', # Session cookie name
        max_age:int=365*24*3600, # Session cookie expiry time
        sess_path:str='/', # Session cookie path
        same_site:str='lax', # Session cookie same site policy
        sess_https_only:bool=False, # Session cookie HTTPS only?
        sess_domain:Optional[str]=None, # Session cookie domain
        htmlkw:Optional[dict]=None, # Attrs to add to the HTML tag
        bodykw:Optional[dict]=None, # Attrs to add to the Body tag
        reload_attempts:Optional[int]=1, # Number of reload attempts when live reloading
        reload_interval:Optional[int]=1000, # Time between reload attempts in ms
        static_path:str=".",  # Where the static file route points to, defaults to root dir
        body_wrap:callable=noop_body, # FT wrapper for body contents
        nb_hdrs:bool=False, # If in notebook include headers inject headers in notebook DOM?
        **kwargs):
    "Create a FastHTML or FastHTMLWithLiveReload app."
    h = (picolink,) if pico or (pico is None and default_hdrs) else ()
    if hdrs: h += tuple(hdrs)

    app = _app_factory(hdrs=h, ftrs=ftrs, before=before, middleware=middleware, live=live, debug=debug, title=title, routes=routes, exception_handlers=exception_handlers,
                  on_startup=on_startup, on_shutdown=on_shutdown, lifespan=lifespan, default_hdrs=default_hdrs, secret_key=secret_key, canonical=canonical,
                  session_cookie=session_cookie, max_age=max_age, sess_path=sess_path, same_site=same_site, sess_https_only=sess_https_only,
                  sess_domain=sess_domain, key_fname=key_fname, exts=exts, surreal=surreal, htmx=htmx, htmx4=htmx4, htmlkw=htmlkw,
                  reload_attempts=reload_attempts, reload_interval=reload_interval, body_wrap=body_wrap, nb_hdrs=nb_hdrs, **(bodykw or {}))
    app.static_route_exts(static_path=static_path)
    if not db_file: return app,app.route

    db = database(db_file)
    if not tbls: tbls={}
    if kwargs:
        if isinstance(first(kwargs.values()), dict): tbls = kwargs
        else:
            kwargs['render'] = render
            tbls['items'] = kwargs
    dbtbls = [_get_tbl(db.t, k, v) for k,v in tbls.items()]
    if len(dbtbls)==1: dbtbls=dbtbls[0]
    return app,app.route,*dbtbls

# %% ../nbs/00_core.ipynb #8701d6cd
def PicoBusy4():
    return (HtmxOn('before:request', "event.detail.ctx.sourceElement.setAttribute('aria-busy', 'true' )"),
            HtmxOn('after:request',  "event.detail.ctx.sourceElement.setAttribute('aria-busy', 'false')"))

# %% ../nbs/00_core.ipynb #d5300905
from inspect import Parameter
empty = Parameter.empty

import fasthtml.core as _core
from fasthtml.core import _send_ws

from typing import Optional, get_type_hints, get_args, get_origin, Union, Mapping, TypedDict, List, Any
from types import UnionType, SimpleNamespace as ns, GenericAlias
from datetime import datetime,date


# %% ../nbs/00_core.ipynb #e1700c31
htmx_exts['ws4'] = 'https://unpkg.com/htmx.org@4.0.0-alpha7/dist/ext/hx-ws.js'

# %% ../nbs/00_core.ipynb #d1c934db
async def _find_p(conn, data, hdrs, arg:str, p:Parameter):
    "In `data` find param named `arg` of type in `p` (`arg` is ignored for body types)"
    anno = p.annotation
    # Special annotation types
    if isinstance(anno, type) and not isinstance(anno, GenericAlias):
        if issubclass(anno, HtmxHeaders): return _get_htmx(hdrs)
        if issubclass(anno, Starlette): return conn.scope['app']
        if issubclass(anno, HTTPConnection): return conn
        if issubclass(anno, State): return conn.scope['app'].state
        if anno is dict: return data
        if _is_body(anno):
            if 'session'.startswith(arg.lower()): return conn.scope.get('session', {})
            return await _from_body(conn, p, data)
    # Special param names with no annotations
    if anno is empty:
        if arg.lower()=='ws' or 'request'.startswith(arg.lower()): return conn
        if 'session'.startswith(arg.lower()): return conn.scope.get('session', {})
        if arg.lower()=='scope': return dict2obj(conn.scope)
        if arg.lower()=='data': return data
        if arg.lower()=='htmx': return _get_htmx(hdrs)
        if arg.lower()=='app': return conn.scope['app']
        if arg.lower()=='state': return conn.scope['app'].state
        if arg.lower()=='auth': return conn.scope.get('auth', None)
        if arg.lower()=='send':
            assert not isinstance(conn, Request), "`send` requires a websocket, not a `Request`"
            return partial(_send_ws, conn)
        if arg.lower()=='api': return ApiReturn(hdrs.get('accept')=='application/json')
        if arg.lower()=='body': return (await conn.body()).decode()
        if arg.lower() in ('hdrs','ftrs','bodykw','htmlkw'): return getattr(conn, arg.lower())
        if arg!='resp': warn(f"`{arg} has no type annotation and is not a recognised special name, so is ignored.")
        return None
    # Not a special name or a special annotation
    res = conn.path_params.get(arg, None)
    if res in (empty,None): res = conn.cookies.get(arg, None)
    if res in (empty,None): res = hdrs.get(snake2hyphens(arg), None)
    if res in (empty,None): res = conn.query_params.getlist(arg)
    if res==[]: res = None
    if res in (empty,None): res = data.get(arg, None)
    if res in (empty, None) and conn.scope['app'].htmx4: res = data.get('values', {}).get(arg, None) 
    if res in (empty,None):
        if p.default is empty:
            if isinstance(conn, Request): raise HTTPException(400, f"Missing required field: {arg}")
            raise ValueError(f"Missing required field: {arg}")
        res = p.default
    if anno is empty: return res
    try: return _fix_anno(anno, res)
    except ValueError as e:
        if isinstance(conn, Request): raise HTTPException(404, f"{conn.url.path}: {e}") from None
        raise

_core._find_p = _find_p

# %% ../nbs/00_core.ipynb #41a9e400
async def _wrap_ws(ws, data, params):
    hdrs = {k.lower().replace('-','_'):v for k,v in (data.pop('HEADERS', {}) or data.pop('headers', {})).items()}
    return await _find_ps(ws, data, hdrs, params)

_core._wrap_ws = _wrap_ws

# %% ../nbs/00_core.ipynb #17aac44d
def sse_message(elm, event='message', htmx4=False):
    "Convert element `elm` into a format suitable for SSE streaming"
    data = '\n'.join(f'data: {o}' for o in to_xml(elm).splitlines())
    # In htmx v4, omitting event: does default swap; including it triggers custom DOM event
    if htmx4 and event == 'message': return f'{data}\n\n'
    return f'event: {event}\n{data}\n\n'

import fasthtml.components
fasthtml.components.sse_message = sse_message
