"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['HTMX_V4_SRC', 'WS_V4_SRC', 'DEFAULT_HTMX_V4_CONFIG', 'htmx_v4', 'ws_v4', 'meta_cfg', 'htmx_v4_hdrs', 'Partial',
           'fast_app_v4']

# %% ../nbs/00_core.ipynb 2
import json
from fastcore.meta import delegates
from fasthtml.common import Meta, Script, fast_app, fhjsscr, ft_hx


# %% ../nbs/00_core.ipynb 3
HTMX_V4_SRC = "https://unpkg.com/htmx.org@4.0.0-alpha6/dist/htmx.js"
WS_V4_SRC = "https://unpkg.com/htmx.org@4.0.0-alpha6/dist/ext/hx-ws.js"
DEFAULT_HTMX_V4_CONFIG = {"metaCharacter": "-"}

# %% ../nbs/00_core.ipynb 4
@delegates(ft_hx)
def Partial(*args, **kwargs): return ft_hx("hx-partial")(*args, **kwargs)


# %% ../nbs/00_core.ipynb 5
htmx_v4 = Script(src=HTMX_V4_SRC)
ws_v4 = Script(src=WS_V4_SRC)
meta_cfg = Meta(name="htmx:config", content=json.dumps(DEFAULT_HTMX_V4_CONFIG))
htmx_v4_hdrs = (meta_cfg, fhjsscr, htmx_v4)


# %% ../nbs/00_core.ipynb 6
def fast_app_v4(*args, htmx=False, hdrs=None, **kwargs):
    """`fast_app` with `htmx=False` + v4 header tags added to `hdrs=`."""
    if hdrs is None: hdrs = []
    elif isinstance(hdrs, (list, tuple)): hdrs = list(hdrs)
    else: hdrs = [hdrs]
    hdrs += list(htmx_v4_hdrs)
    return fast_app(*args, htmx=htmx, hdrs=hdrs, **kwargs)
