[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fasthtml-htmxv4-patch"
version = "0.0.1"
description = "Tiny helpers to use htmx v4 (alpha) with python-fasthtml"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["python-fasthtml", "fastcore"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["fasthtml_htmxv4_patch*"]
